name: "Setup Python and UV"
description: "Sets up Python and UV"
inputs:
  python-version:
    description: "Python version to set up"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up uv
      shell: sh
      run: make install-uv

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore uv cache
      id: cache
      uses: actions/cache@v4
      with:
        path: /tmp/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          uv-${{ runner.os }}
